spring:
  application:
    name: OneDrop

---
# no-database profile for dev
spring:
  config:
    activate:
      on-profile: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 9090


  spring:
    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
  logging:
    level:
      web: info


---
# MySQL profile for prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://<HOST>:3306/onedrop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
